steps:
# Docker Build on Cloud Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central-docker.pkg.dev/$PROJECT_ID/falopez-cymbal-coffee-dotnet/cymbalcoffee:$SHORT_SHA', '.']
 
# Docker Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central-docker.pkg.dev/$PROJECT_ID/falopez-cymbal-coffee-dotnet/cymbalcoffee:$SHORT_SHA'] 

# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'falopez-cymbal-coffee-dotnet',
    '--image', 'us-central-docker.pkg.dev/$PROJECT_ID/falopez-cymbal-coffee-dotnet/cymbalcoffee:$SHORT_SHA',
    '--region', 'us-central',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--port', '80']

