apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: cloud-run-app
profiles:
- name: cr-dev
  manifests:
    rawYaml:
    - deploy/cloudrun/deploy-dev.yaml
- name: cr-qa
  manifests:
    rawYaml:
    - deploy/cloudrun/deploy-qa.yaml
- name: cr-prod
  manifests:
    rawYaml:
    - deploy/cloudrun/deploy-prod.yaml
deploy:
  cloudrun: {}